version: "3"
services:
  db:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db/database:/var/lib/mysql
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolists
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    #   MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  web:
    build: ./web
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: dbuser
      DB_PASSWORD: dbpass